export const SET_ACCOUNT = "SET_ACCOUNT";
export const UPDATE_COMPOSE_MESSAGE = "UPDATE_COMPOSE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const REHYDRATE_CUSTOMER_DETAILS = "REHYDRATE_CUSTOMER_DETAILS";